package cn.demo.appq.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.demo.appq.entity.ReqEntity;

import cn.demo.appq.greendao.ReqEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reqEntityDaoConfig;

    private final ReqEntityDao reqEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reqEntityDaoConfig = daoConfigMap.get(ReqEntityDao.class).clone();
        reqEntityDaoConfig.initIdentityScope(type);

        reqEntityDao = new ReqEntityDao(reqEntityDaoConfig, this);

        registerDao(ReqEntity.class, reqEntityDao);
    }
    
    public void clear() {
        reqEntityDaoConfig.clearIdentityScope();
    }

    public ReqEntityDao getReqEntityDao() {
        return reqEntityDao;
    }

}
