package cn.demo.appq.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.demo.appq.entity.ReqEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NETWORK_REQUEST_DETAILED".
*/
public class ReqEntityDao extends AbstractDao<ReqEntity, Long> {

    public static final String TABLENAME = "NETWORK_REQUEST_DETAILED";

    /**
     * Properties of entity ReqEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SessionId = new Property(1, String.class, "sessionId", false, "SESSION_ID");
        public final static Property AppName = new Property(2, String.class, "appName", false, "APP_NAME");
        public final static Property AppPackage = new Property(3, String.class, "appPackage", false, "APP_PACKAGE");
        public final static Property AppVersion = new Property(4, String.class, "appVersion", false, "APP_VERSION");
        public final static Property AppVersionCode = new Property(5, String.class, "appVersionCode", false, "APP_VERSION_CODE");
        public final static Property Url = new Property(6, String.class, "url", false, "URL");
        public final static Property Host = new Property(7, String.class, "host", false, "HOST");
        public final static Property Port = new Property(8, Integer.class, "port", false, "PORT");
        public final static Property Index = new Property(9, Integer.class, "index", false, "INDEX");
        public final static Property Ip = new Property(10, String.class, "ip", false, "IP");
        public final static Property Protocol = new Property(11, String.class, "protocol", false, "PROTOCOL");
        public final static Property HttpProtocol = new Property(12, String.class, "httpProtocol", false, "HTTP_PROTOCOL");
        public final static Property Method = new Property(13, String.class, "method", false, "METHOD");
        public final static Property Path = new Property(14, String.class, "path", false, "PATH");
        public final static Property IsHttps = new Property(15, Boolean.class, "isHttps", false, "IS_HTTPS");
        public final static Property Time = new Property(16, Long.class, "time", false, "TIME");
        public final static Property Uid = new Property(17, Integer.class, "uid", false, "UID");
        public final static Property Length = new Property(18, Integer.class, "length", false, "LENGTH");
        public final static Property StreamId = new Property(19, Integer.class, "streamId", false, "STREAM_ID");
        public final static Property RequestHeaders = new Property(20, String.class, "requestHeaders", false, "REQUEST_HEADERS");
        public final static Property ClientHttp2Settings = new Property(21, String.class, "clientHttp2Settings", false, "CLIENT_HTTP2_SETTINGS");
        public final static Property PeerHttp2Settings = new Property(22, String.class, "peerHttp2Settings", false, "PEER_HTTP2_SETTINGS");
        public final static Property ReqContent = new Property(23, String.class, "reqContent", false, "REQ_CONTENT");
        public final static Property RespContent = new Property(24, String.class, "respContent", false, "RESP_CONTENT");
        public final static Property RespMessage = new Property(25, String.class, "respMessage", false, "RESP_MESSAGE");
        public final static Property RespCode = new Property(26, Integer.class, "respCode", false, "RESP_CODE");
        public final static Property IsWebSocket = new Property(27, Boolean.class, "isWebSocket", false, "IS_WEB_SOCKET");
        public final static Property NetType = new Property(28, String.class, "netType", false, "NET_TYPE");
        public final static Property RequestBodyOffset = new Property(29, int.class, "requestBodyOffset", false, "REQUEST_BODY_OFFSET");
        public final static Property ResponseBodyOffset = new Property(30, int.class, "responseBodyOffset", false, "RESPONSE_BODY_OFFSET");
    }


    public ReqEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ReqEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NETWORK_REQUEST_DETAILED\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SESSION_ID\" TEXT," + // 1: sessionId
                "\"APP_NAME\" TEXT," + // 2: appName
                "\"APP_PACKAGE\" TEXT," + // 3: appPackage
                "\"APP_VERSION\" TEXT," + // 4: appVersion
                "\"APP_VERSION_CODE\" TEXT," + // 5: appVersionCode
                "\"URL\" TEXT," + // 6: url
                "\"HOST\" TEXT," + // 7: host
                "\"PORT\" INTEGER," + // 8: port
                "\"INDEX\" INTEGER," + // 9: index
                "\"IP\" TEXT," + // 10: ip
                "\"PROTOCOL\" TEXT," + // 11: protocol
                "\"HTTP_PROTOCOL\" TEXT," + // 12: httpProtocol
                "\"METHOD\" TEXT," + // 13: method
                "\"PATH\" TEXT," + // 14: path
                "\"IS_HTTPS\" INTEGER," + // 15: isHttps
                "\"TIME\" INTEGER," + // 16: time
                "\"UID\" INTEGER," + // 17: uid
                "\"LENGTH\" INTEGER," + // 18: length
                "\"STREAM_ID\" INTEGER," + // 19: streamId
                "\"REQUEST_HEADERS\" TEXT," + // 20: requestHeaders
                "\"CLIENT_HTTP2_SETTINGS\" TEXT," + // 21: clientHttp2Settings
                "\"PEER_HTTP2_SETTINGS\" TEXT," + // 22: peerHttp2Settings
                "\"REQ_CONTENT\" TEXT," + // 23: reqContent
                "\"RESP_CONTENT\" TEXT," + // 24: respContent
                "\"RESP_MESSAGE\" TEXT," + // 25: respMessage
                "\"RESP_CODE\" INTEGER," + // 26: respCode
                "\"IS_WEB_SOCKET\" INTEGER," + // 27: isWebSocket
                "\"NET_TYPE\" TEXT," + // 28: netType
                "\"REQUEST_BODY_OFFSET\" INTEGER NOT NULL ," + // 29: requestBodyOffset
                "\"RESPONSE_BODY_OFFSET\" INTEGER NOT NULL );"); // 30: responseBodyOffset
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NETWORK_REQUEST_DETAILED\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReqEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(2, sessionId);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(3, appName);
        }
 
        String appPackage = entity.getAppPackage();
        if (appPackage != null) {
            stmt.bindString(4, appPackage);
        }
 
        String appVersion = entity.getAppVersion();
        if (appVersion != null) {
            stmt.bindString(5, appVersion);
        }
 
        String appVersionCode = entity.getAppVersionCode();
        if (appVersionCode != null) {
            stmt.bindString(6, appVersionCode);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
 
        String host = entity.getHost();
        if (host != null) {
            stmt.bindString(8, host);
        }
 
        Integer port = entity.getPort();
        if (port != null) {
            stmt.bindLong(9, port);
        }
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(10, index);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(11, ip);
        }
 
        String protocol = entity.getProtocol();
        if (protocol != null) {
            stmt.bindString(12, protocol);
        }
 
        String httpProtocol = entity.getHttpProtocol();
        if (httpProtocol != null) {
            stmt.bindString(13, httpProtocol);
        }
 
        String method = entity.getMethod();
        if (method != null) {
            stmt.bindString(14, method);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(15, path);
        }
 
        Boolean isHttps = entity.getIsHttps();
        if (isHttps != null) {
            stmt.bindLong(16, isHttps ? 1L: 0L);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(17, time);
        }
 
        Integer uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(18, uid);
        }
 
        Integer length = entity.getLength();
        if (length != null) {
            stmt.bindLong(19, length);
        }
 
        Integer streamId = entity.getStreamId();
        if (streamId != null) {
            stmt.bindLong(20, streamId);
        }
 
        String requestHeaders = entity.getRequestHeaders();
        if (requestHeaders != null) {
            stmt.bindString(21, requestHeaders);
        }
 
        String clientHttp2Settings = entity.getClientHttp2Settings();
        if (clientHttp2Settings != null) {
            stmt.bindString(22, clientHttp2Settings);
        }
 
        String peerHttp2Settings = entity.getPeerHttp2Settings();
        if (peerHttp2Settings != null) {
            stmt.bindString(23, peerHttp2Settings);
        }
 
        String reqContent = entity.getReqContent();
        if (reqContent != null) {
            stmt.bindString(24, reqContent);
        }
 
        String respContent = entity.getRespContent();
        if (respContent != null) {
            stmt.bindString(25, respContent);
        }
 
        String respMessage = entity.getRespMessage();
        if (respMessage != null) {
            stmt.bindString(26, respMessage);
        }
 
        Integer respCode = entity.getRespCode();
        if (respCode != null) {
            stmt.bindLong(27, respCode);
        }
 
        Boolean isWebSocket = entity.getIsWebSocket();
        if (isWebSocket != null) {
            stmt.bindLong(28, isWebSocket ? 1L: 0L);
        }
 
        String netType = entity.getNetType();
        if (netType != null) {
            stmt.bindString(29, netType);
        }
        stmt.bindLong(30, entity.getRequestBodyOffset());
        stmt.bindLong(31, entity.getResponseBodyOffset());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReqEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(2, sessionId);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(3, appName);
        }
 
        String appPackage = entity.getAppPackage();
        if (appPackage != null) {
            stmt.bindString(4, appPackage);
        }
 
        String appVersion = entity.getAppVersion();
        if (appVersion != null) {
            stmt.bindString(5, appVersion);
        }
 
        String appVersionCode = entity.getAppVersionCode();
        if (appVersionCode != null) {
            stmt.bindString(6, appVersionCode);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
 
        String host = entity.getHost();
        if (host != null) {
            stmt.bindString(8, host);
        }
 
        Integer port = entity.getPort();
        if (port != null) {
            stmt.bindLong(9, port);
        }
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(10, index);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(11, ip);
        }
 
        String protocol = entity.getProtocol();
        if (protocol != null) {
            stmt.bindString(12, protocol);
        }
 
        String httpProtocol = entity.getHttpProtocol();
        if (httpProtocol != null) {
            stmt.bindString(13, httpProtocol);
        }
 
        String method = entity.getMethod();
        if (method != null) {
            stmt.bindString(14, method);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(15, path);
        }
 
        Boolean isHttps = entity.getIsHttps();
        if (isHttps != null) {
            stmt.bindLong(16, isHttps ? 1L: 0L);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(17, time);
        }
 
        Integer uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(18, uid);
        }
 
        Integer length = entity.getLength();
        if (length != null) {
            stmt.bindLong(19, length);
        }
 
        Integer streamId = entity.getStreamId();
        if (streamId != null) {
            stmt.bindLong(20, streamId);
        }
 
        String requestHeaders = entity.getRequestHeaders();
        if (requestHeaders != null) {
            stmt.bindString(21, requestHeaders);
        }
 
        String clientHttp2Settings = entity.getClientHttp2Settings();
        if (clientHttp2Settings != null) {
            stmt.bindString(22, clientHttp2Settings);
        }
 
        String peerHttp2Settings = entity.getPeerHttp2Settings();
        if (peerHttp2Settings != null) {
            stmt.bindString(23, peerHttp2Settings);
        }
 
        String reqContent = entity.getReqContent();
        if (reqContent != null) {
            stmt.bindString(24, reqContent);
        }
 
        String respContent = entity.getRespContent();
        if (respContent != null) {
            stmt.bindString(25, respContent);
        }
 
        String respMessage = entity.getRespMessage();
        if (respMessage != null) {
            stmt.bindString(26, respMessage);
        }
 
        Integer respCode = entity.getRespCode();
        if (respCode != null) {
            stmt.bindLong(27, respCode);
        }
 
        Boolean isWebSocket = entity.getIsWebSocket();
        if (isWebSocket != null) {
            stmt.bindLong(28, isWebSocket ? 1L: 0L);
        }
 
        String netType = entity.getNetType();
        if (netType != null) {
            stmt.bindString(29, netType);
        }
        stmt.bindLong(30, entity.getRequestBodyOffset());
        stmt.bindLong(31, entity.getResponseBodyOffset());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReqEntity readEntity(Cursor cursor, int offset) {
        ReqEntity entity = new ReqEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sessionId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // appName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // appPackage
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // appVersion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // appVersionCode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // url
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // host
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // port
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // index
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ip
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // protocol
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // httpProtocol
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // method
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // path
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // isHttps
            cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16), // time
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // uid
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18), // length
            cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // streamId
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // requestHeaders
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // clientHttp2Settings
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // peerHttp2Settings
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // reqContent
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // respContent
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // respMessage
            cursor.isNull(offset + 26) ? null : cursor.getInt(offset + 26), // respCode
            cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0, // isWebSocket
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // netType
            cursor.getInt(offset + 29), // requestBodyOffset
            cursor.getInt(offset + 30) // responseBodyOffset
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReqEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSessionId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAppName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAppPackage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAppVersion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAppVersionCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHost(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPort(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setIndex(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIp(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setProtocol(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setHttpProtocol(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMethod(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPath(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setIsHttps(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setTime(cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16));
        entity.setUid(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setLength(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
        entity.setStreamId(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setRequestHeaders(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setClientHttp2Settings(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPeerHttp2Settings(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setReqContent(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setRespContent(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setRespMessage(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setRespCode(cursor.isNull(offset + 26) ? null : cursor.getInt(offset + 26));
        entity.setIsWebSocket(cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0);
        entity.setNetType(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setRequestBodyOffset(cursor.getInt(offset + 29));
        entity.setResponseBodyOffset(cursor.getInt(offset + 30));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReqEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReqEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReqEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
